// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRV-TwmLmhEoJYokAWLDUYFXeCko4KRgg',
    appId: '1:1042710793896:web:04c5b70c4c60f07b8c7c9d',
    messagingSenderId: '1042710793896',
    projectId: 'firstapp-skm',
    authDomain: 'firstapp-skm.firebaseapp.com',
    storageBucket: 'firstapp-skm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3po-VIYrBeoZBCEp4lxpYzZduxeBHBuo',
    appId: '1:1042710793896:android:fc1b1a583e3e05bc8c7c9d',
    messagingSenderId: '1042710793896',
    projectId: 'firstapp-skm',
    storageBucket: 'firstapp-skm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8b7UrkCCRx4aWCxSHBQxfzVfE8ghsHLE',
    appId: '1:1042710793896:ios:c9ca065906800a588c7c9d',
    messagingSenderId: '1042710793896',
    projectId: 'firstapp-skm',
    storageBucket: 'firstapp-skm.appspot.com',
    iosClientId: '1042710793896-o54rcae6ae8p4aknqa4a5arm1ffpnble.apps.googleusercontent.com',
    iosBundleId: 'com.skm.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8b7UrkCCRx4aWCxSHBQxfzVfE8ghsHLE',
    appId: '1:1042710793896:ios:50ccf7feddda10088c7c9d',
    messagingSenderId: '1042710793896',
    projectId: 'firstapp-skm',
    storageBucket: 'firstapp-skm.appspot.com',
    iosClientId: '1042710793896-oi9hid7f162hct8n0urr2hkpl5r29jua.apps.googleusercontent.com',
    iosBundleId: 'com.skm.firstapp.RunnerTests',
  );
}
